version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: insurance-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Macky@21
      MYSQL_DATABASE: xyz
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend/HealthInsurance
      dockerfile: Dockerfile
    container_name: insurance-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/xyz?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Macky@21
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: insurance-frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"

volumes:
  db_data:
