apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-frontend
  labels:
    app: insurance-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-frontend
  template:
    metadata:
      labels:
        app: insurance-frontend
    spec:
      containers:
        - name: insurance-frontend
          image: neha676/insurance-frontend:latest   
          ports:
            - containerPort: 80                      
          imagePullPolicy: Always
